---
- name:Gather facts and display it
  hosts: my_random_host
  tasks:
  - name: Display all gather facts
    ansible.builtin.debug:
      var: ansible_facts
      
  - name: Display the currentlty running kernel version and distribution
    ansible.builtin.debug:
      msg: "The kernel version is{{ansible_facts.kernel}} and the distribution is {{ansible_facts.distribution}}"